# Add path of the theme
fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit

export TERM=xterm-256color

export NIX_BUILD_SHELL=$(which zsh)

# load plugins
source $HOME/.zsh/plugins/zsh-nix-shell/nix-shell.plugin.zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/prestonh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Enable zoxide and fuzzy-finder (fzf)
eval "$(zoxide init zsh --cmd cd)"

alias ls=lsd

# The Fuck
eval $(thefuck --alias)

# Custom ls aliases
alias lt="ls -latr"
alias lll="l --color=always | less -R"
alias ltl="lt --color=always | less -R"

# Allow git access as root using user configs
alias gsudo='sudo git -c "include.path='"${XDG_CONFIG_DIR:-$HOME/.config}/git/config\" -c \"include.path=$HOME/.gitconfig\""
# Do the same for neovim
alias nvims="sudo XDG_CONFIG_HOME=\"$HOME/.config/\" nvim"
#-u ${XDG_CONFIG_DIR:-$HOME/.config}/nvim/init.lua"

# Exclude certain directories when using the `tree` command
export TREE_EXCLUDE="target"
alias tree="tree -I '$TREE_EXCLUDE'"

# Add directories to the user path
export PATH="$PATH:$HOME/.npm/bin"

# This should probably be the last line in this file
prompt pure

